name: Label Watcher

on:
  pull_request:
    # Other types listed here: https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#pull_request
    types: [ unlabeled ]

  # Allows manual triggering
  workflow_dispatch:

jobs:
  check:
    # If the pull request is not a draft, and the label that has just been removed is 'wip', then trigger the pipeline
    if: ${{ github.event.pull_request.draft != true && github.event.label.name == 'wip' }}
    runs-on: ubuntu-latest
    steps:
      # Allows the action to access repository code, in this case, the pipeline_trigger action itself
      - uses: actions/checkout@v2
      - uses: justeat/fozzie-components/.github/actions/pipeline_trigger
